Add basic logging and answer file

diff --git a/somail-config-more b/somail-config-more
--- a/somail-config-more
+++ b/somail-config-more
@@ -4,6 +4,7 @@
 # Variables
 #########################################
 DEBUG="0"
+LOG=`mktemp /tmp/so-email-setup.log.XXXXXXXXXX`
 HOSTNAME=`hostname`
 IP=`ifconfig |grep "inet addr" | awk '{print $2}' |cut -d\: -f2 |grep -v "127.0.0.1" |head -1`
 TITLE="Security Onion Email Setup ($HOSTNAME)"
@@ -21,6 +22,16 @@ SGUILSUMMARY="Not Configured"
 ELSASUMMARY="Not Configured"
 ELSAUSER="Not Configured"
 ELSASERVER="Not Configured"
+#########################################
+# Got r00t?
+#########################################
+if [[ $(/usr/bin/id -u) -ne 0 && "$1" != "-w" ]]; then
+    echo "Email Setup needs to be run as root.  Please try again using sudo."
+    zenity --error --title "$TITLE" --text="Email Setup needs to be run as root.  Please try again using sudo."
+    exit
+fi
+
+function ask() {
 #########################################
 # Welcome Screen
 #########################################
@@ -248,6 +259,12 @@ if [ $ANSWER -eq 1 ]; then
 else
         [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuration confirmed."
 fi
+}
+function MOVELOG() {
+# Move log file from /tmp/ to /var/log/nsm/
+mv $LOG /var/log/nsm/so-email-setup.log
+LOG="/var/log/nsm/so-email-setup.log"
+}
 
 #########################################
 # Begin function CONFIGURE_EMAIL
@@ -258,7 +275,7 @@ function CONFIGURE_EMAIL() {
 if dpkg -l | grep -q -i "mailutils"; then
         :
 else
-	apt-get install -y mailutils > /dev/null 2>&1
+	apt-get install -y mailutils > $LOG 2>&1
 fi
 
 echo "10"
@@ -270,14 +287,13 @@ if  grep -q "root:" $ALIASES;then
 else
         sed -i "/postmaster/a root: $NOTIFYADDRESS" $ALIASES
 fi
-newaliases > /dev/null 2>&1
+newaliases > $LOG 2>&1
 #Configure system from address
 POSTFIX="/etc/postfix/main.cf"
 #Configure system mail server
 sed -i "s|^relayhost = .*$|relayhost = $MAILSERVER|g" $POSTFIX
-#Configure loopback-only so that Posfix listens to localhost only
 sed -i "s|^inet_interfaces = .*$|inet_interfaces = loopback-only|g" $POSTFIX
-service postfix restart > /dev/null 2>&1
+service postfix restart > $LOG 2>&1
 #Configure sostat
 echo "15"
 echo "# Configuring sostat mail..."
@@ -291,7 +307,7 @@ echo "30"
 echo "# Configuring Bro email..."
 if ! [[ "$BROSUMMARY" == "Not Configured" ]]; then
 	BROCTL="/opt/bro/etc/broctl.cfg"
-	sed -i "s|^MailTo.*$|MailTo = $BROADDRESS|g" $BROCTL
+	sed -i "s|^MailTo.*$|MailTo = root@localhost|g" $BROCTL
         if grep -q "tracesummary=" $BROCTL;then
         	sed -i "s|^tracesummary=.*$|tracesummary=|g" $BROCTL
 	else
@@ -303,7 +319,7 @@ if ! [[ "$BROSUMMARY" == "Not Configured" ]]; then
         else
         	echo -e "\n# Bro Notice email configuration\nhook Notice::policy(n: Notice::Info)\n             {       \n      add n\$actions[Notice::ACTION_ALARM];\n         }" >> $LOCALBRO
         fi
-	nsm_sensor_ps-restart --only-bro > /dev/null
+	nsm_sensor_ps-restart --only-bro > $LOG 2>&1
 fi
 #Configure Sguil
 echo "45"
@@ -315,9 +331,8 @@ if ! [[ "$SGUILSUMMARY" == "Not Configured" ]]; then
         sed -i "s|^set SMTP.*$|set SMTP_SERVER localhost|g" $SGUILDEMAIL
         sed -i "s|^set EMAIL_RCPT.*$|set EMAIL_RCPT_TO \"root@localhost\"|g" $SGUILDEMAIL
         sed -i "s|^set EMAIL_FROM.*$|set EMAIL_FROM \"Sguil\"|g" $SGUILDEMAIL
-	nsm_server_ps-restart > /dev/null
+	nsm_server_ps-restart > $LOG 2>&1
 fi
-echo $FROMADDRESS
 #Configure OSSEC
 echo "60"
 echo "# Configuring OSSEC email..."
@@ -335,7 +350,7 @@ if ! [[ "$OSSECSUMMARY" == "Not Configured" ]]; then
                 sed -i '/.*smtp_server.*/ a \     <email_from>no-reply<\/email_from>' $OSSECCONF
                 sed -i '/.*email_from.*/ a \     <email_maxperhour>\100\<\/email_maxperhour>' $OSSECCONF
         fi
-	service ossec-hids-server restart > /dev/null
+	service ossec-hids-server restart > $LOG 2>&1
 fi
 #Configure ELSA
 echo "75"
@@ -350,15 +365,105 @@ if ! [[ "$ELSASUMMARY" == "Not Configured" ]]; then
         else
                 sed -i '/.*base_url.*/ a \    "smtp_server": "localhost",' $ELSAWEB
         fi
-	service apache2 restart > /dev/null 2>&1
+	service apache2 restart > $LOG 2>&1
 fi
 }
-CONFIGURE_EMAIL | zenity --progress --title="$TITLE" --text="Please wait while making changes to the system..." --percentage=0 --auto-close
+#########################################
+# Options
+#########################################
+
+usage()
+{
+cat <<EOF
+
+Security Onion Email Setup
+
+     Options:
+
+        -h              This message
+        -f <file>       Configure using answer file <file>
+
+Usage: $0
+EOF
+}
+# Check to see if the user provided an answer file
+while getopts "hf:" OPTION
+do
+     case $OPTION in
+         h)
+                usage
+                exit 0
+                ;;
+         f)
+                ANSWERFILE="$OPTARG"
+                # Verify answer file exists and then read it into memory
+                if [ ! -f "$ANSWERFILE" ]; then
+                        echo "Error accessing $ANSWERFILE"
+                        exit 1
+                fi
+             ;;
+     esac
+done
+
+# GUI (Zenity) or CLI?
+# Default to zenity
+OUTPUT="gui"
+# If no X11, then fall back to cli
+[ -z "$DISPLAY" ] && OUTPUT="cli"
+# If user provided an answer file, set to cli
+[ -f "$ANSWERFILE" ] && OUTPUT="cli"
+# If the user didn't provide an answer file, then ask them the questions
+if [ ! -f "$ANSWERFILE" ]; then
+        if [ "$OUTPUT" = "gui" ] ; then
+                ask
+        else
+                echo
+                echo "No X display found."
+                echo
+                echo "You'll need to either:"
+                echo
+                echo "- use SSH X-forwarding (ssh -X)"
+                echo
+                echo "OR"
+                echo
+                echo "- use an answer file (sudo sosetup -f so-email-setup.conf)"
+                echo
+                usage
+                exit 0
+        fi
+else
+        source "$ANSWERFILE"
+        echo
+        echo "Security Onion Email Setup"
+        echo
+        echo "Ready to configure system using parameters in $ANSWERFILE."
+        echo
+        echo "WARNING! Continuing will destroy any existing data/config."
+        echo "Are you sure you want to continue?"
+        echo "Type yes to continue or anything else to exit."
+        read INPUT
+        [ "$INPUT" != "yes" ] && exit 0
+        echo
+fi
+if [ "$OUTPUT" = "gui" ]; then
+	CONFIGURE_EMAIL |
+	zenity --progress --title="$TITLE" --text="Please wait while making changes to the system..." --percentage=0 --auto-close
+else
+        echo "Please wait while..."
+        CONFIGURE_EMAIL | grep --line-buffered "^#" | sed 's|# Please wait while||g'
+fi
+MOVELOG
 ########################################
 # Setup Complete
 ########################################
-TEXT="<b>Security Onion Email Setup is now complete!</b> \n \
-\n \
+TEXT="Security Onion Email Setup is now complete! \n \
+\n\
 If you would like to edit the email configuration manually, please refer to:\n
 https://github.com/Security-Onion-Solutions/security-onion/wiki/Email\n"
-zenity --info --title="$TITLE" --text="$TEXT" --no-wrap
+        if [ "$OUTPUT" = "gui" ]; then
+		zenity --info --title="$TITLE" --text="$TEXT" --no-wrap
+        else
+                echo
+                echo "$TEXT" | sed 's|\\n|\n|g' | sed 's|\\||g'
+                echo
+        fi
